[package]
name = "metalmorphosis"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
levitate = "0.1.2"
serde = "1.0.144"
serde_derive = "1.0.144"
thiserror = "1.0.35"
tokio = { version = "1.21.2", features = ["net"] }

[profile.release]
codegen-units = 1
lto = true
